apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: offerfy-dev
  namespace: argocd
spec:
  project: offerfy
  source:
    repoURL: https://github.com/ruby0322/offerfy.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: offerfy-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
